Vagrant.configure("2") do |config|

  config.vm.define "server" do |server|
  #config maquina
    server.vm.box = "generic/debian10"
    server.vm.hostname = "minedebian"
    server.vm.network "forwarded_port", guest: 25565, host: 25565
    
  #copiar fich
    server.vm.provision "shell", inline: "mkdir /master"
    server.vm.provision "shell", inline: "chmod 777 /master"
    server.vm.provision "file", source: "./master/", destination: "/master"
    server.vm.provision :shell, path: "install.sh"
    
    server.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 4096]
      v.customize ["modifyvm", :id, "--name", "minedebian"]
      v.customize ["modifyvm", :id, "--cpus", 4]
    end
  end
  
end
